services:
  app:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "3333:3000"
    depends_on:
      - redis
    environment:
      - RAILS_ENV=development
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379/0
  redis:
    image: redis:alpine
